### ISSUE TITLE
Linux is case sensitive, so one folder needs to be renamed

### ISSUE THREAD

**Issue by aboutafter** [HyperspaceMadness/shaders_slang#1]
The folder /HyperspaceMadness needs to be renamed to all lowercase on Linux for it to work, like it's called in the .slangp files. It was all in lowercase previously but got changed like a month or two ago. 

/shaders_slang/crt/shaders/HyperspaceMadness/
to
/shaders_slang/crt/shaders/hyperspacemadness/

**Comment by HyperspaceMadness** [comment]
So renaming the includes would also work?

**Comment by aboutafter** [comment]
I'm seeing that, for example, in the [hsm-mega-screen-scale-crt-royale.slangp](https://github.com/HyperspaceMadness/shaders_slang/blob/master/crt/hsm-mega-screen-scale-crt-royale.slangp) you have both folder names on the shader passes, so the correct way to fix this would be to change the shader addresses there.

**Comment by HyperspaceMadness** [comment]
This has been fixed in the latest commit, enjoy! :)
